/**
 * Represents the lifecycle state of an entity managed by geto.
 */
export enum EEntityState {
  /** The entity has been consumed and its representation persisted. */
  STORED = 'stored',
  /** The adapter release hook has been executed on the original resource. */
  RELEASED = 'released',
  /** The entity has been removed from storage; terminal lifecycle state. */
  DELETED = 'deleted',
}

/**
 * Fundamental consumption semantics supported across geto adapters.
 */
export enum EConsumptionSemantic {
  /** Creates an independent copy of the resource representation. */
  COPY = 'copy',
  /** Takes temporary ownership/control over a resource lifecycle. */
  CAPTURE = 'capture',
  /** Converts an arbitrary resource into a persistable format. */
  SERIALIZE = 'serialize',
  /** Wraps an active live resource handle with management capabilities. */
  WRAP = 'wrap',
  /** Stores a reference/locator; resolves the concrete resource upon restoration. */
  REGISTER = 'register',
}

/**
 * Metadata descriptor for an entity.
 */
export interface IEntityMetadata {
  /** Unique entity identifier. */
  id: string;
  /** Identifier of the adapter that consumed this resource. */
  adapterId: string;
  /** Creation timestamp. */
  createdAt: Date;
  /** Last update timestamp. */
  updatedAt: Date;
  /** Optional size in bytes or items if reported by adapter. */
  size?: number;
  /** Developer-defined custom metadata key-values. */
  custom?: Record<string, unknown>;
}

/**
 * Public immutable descriptor for a consumed resource.
 */
export interface IEntity {
  /** Unique identifier generated by the gateway. */
  readonly id: string;
  /** Identifier of the originating adapter. */
  readonly adapterId: string;
  /** Current lifecycle state. */
  readonly state: EEntityState;
  /** Entity metadata. */
  readonly metadata: IEntityMetadata;
  /** Creation timestamp. */
  readonly createdAt: Date;
  /** Last update timestamp. */
  readonly updatedAt: Date;
}

/**
 * Contract defining how a resource type `T` is transformed, stored, and restored as representation `R`.
 *
 * @typeParam T - The original resource type (e.g. Buffer, object, stream).
 * @typeParam R - The stored representation type (e.g. Buffer, string, snapshot).
 */
export interface IGetoAdapter<T, R> {
  /** Unique name or key identifying this adapter implementation. */
  readonly adapterId: string;
  /** Consumption semantic(s) demonstrated by this adapter. */
  readonly semantic: EConsumptionSemantic | EConsumptionSemantic[];
  /**
   * Transforms an input resource into a storable representation.
   *
   * @param resource - Input resource of type `T`.
   * @returns A promise resolving to the representation of type `R`.
   */
  consume(resource: T): Promise<R>;
  /**
   * Restores a stored representation back into the original resource format.
   *
   * @param data - Stored representation of type `R`.
   * @returns A promise resolving to the restored resource of type `T`.
   */
  restore(data: R): Promise<T>;
  /**
   * Optional lifecycle hook to close, detach, or cleanup the resource when released.
   *
   * @param resource - Live or reconstructed resource of type `T`.
   */
  release?(resource: T): Promise<void>;
}

/**
 * Storage backend abstraction for persisting representations by identifier.
 */
export interface IGetoStorage {
  /**
   * Saves arbitrary data by entity ID.
   *
   * @param id - Entity identifier.
   * @param data - The representation payload to store.
   */
  save(id: string, data: unknown): Promise<void>;
  /**
   * Loads the representation associated with an entity ID.
   *
   * @param id - Entity identifier.
   * @returns The stored representation.
   */
  load(id: string): Promise<unknown>;
  /**
   * Removes an entity representation from storage.
   *
   * @param id - Entity identifier.
   */
  delete(id: string): Promise<void>;
  /**
   * Checks whether an entity ID is persisted.
   *
   * @param id - Entity identifier.
   */
  exists(id: string): Promise<boolean>;
}

/**
 * Options passed to `GetoGateway.consume()`.
 */
export interface IConsumeOptions {
  /** Optional custom metadata attached to the created entity. */
  metadata?: Record<string, unknown>;
}

/**
 * Initialization options for {@link GetoGateway}.
 */
export interface IGatewayOptions {
  /** The storage provider to use for representations. */
  storage: IGetoStorage;
  /**
   * Optional upper limit on the number of DELETED entity tombstones retained in memory.
   * When exceeded upon deletion, the oldest tombstones are pruned automatically.
   */
  maxTombstones?: number;
}
